project:
  type: book

book:
  title: "Environmental Statistics Book"
  author: "Professor Bravo"
  date: "2/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter0_RIntro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

