# **Introduction**

## Why Environmental Statistics?

Statistics is a fundamental science in many applications. Normally we observe or collect data from an experiment, a phenomenon, an ecosystem, a population, and we use statistics for collecting, describing, visualizing, modelling, interpreting and predicting important variables associated with the study problem.

The development of environmental statistics as a specific branch or section within statistics has dramatically grown in the past 25 years. The need for applications of a wide range of methods adapted to solve the complexities of environmental data collection, modeling and prediction has been recognized by many institutions worldwide. Many national and international statistical societies as the American Statistical Association ([ASA](https://www.amstat.org/)), the International Statistical Institute ([ISI](https://isi-web.org/)), the Royal Statistical Society ([RSS](https://rss.org.uk/)), the International Society of Bayesian Analysis ([ISBA](https://bayesian.org/)) and Statistical Society of Australia ([SSA](https://www.statsoc.org.au/)) have a devoted section to environmental statistics.

The application of Statistics to analyze environmental issues requires using a variety of tools and methodologies raging from Multivariate Analysis, Time Series analysis to Spatial Statistics. Emerging machine learning methods are playing an important role in scaling up many of the problems involving large data sets and complex inference procedures. Each application requires specific tools, and data exploration and visualization are necessary first steps to understand potential assumptions on probabilistic models to fit collected data.

## Most pressing Environmental problems of our times

Environmental Statistics has a wide range of applications and offers a variety of tools to solve some of the most important environmental problems of our times:

- Biodiversity Loss: Many plant and animal species are rapidly disappearing due to the increment of human activities and environmental degradation. [https://www.europarl.europa.eu/news/en/headlines/society/20200109STO69929/biodiversity-loss-what-is-causing-it-and-why-is-it-a-concern](URL)
- Air pollution, or the release of pollutants into the air, has negative impacts on human health. The World Health Organization (WHO) estimates that nine out of ten people breath air with toxic pollutants exceeding the recommended thresholds by the WHO. [https://www.nrdc.org/stories/air-pollution-everything-you-need-know](URL)
- Water pollution, or the release of chemicals or microorganisms into water reservoirs like streams, rivers, lakes, aquifers, oceans or any other water bodies, has become a public health issue worldwide. Water pollution sources from human activities include agriculture, sewage and waste water, oil pollution/spills, radioactive waste. These sources of pollution would affect groundwater, surface water and oceans. [https://www.nrdc.org/stories/water-pollution-everything-you-need-know](URL)
- Ecosystems degradation including habitat losses, loss of biodiversity and the spread of invasive, species [https://www.sciencedirect.com/science/article/pii/B9780128227947000083](URL) have important consequences on the availability of ecosystem services with harmful impacts on minorities and vulnerable populations. [https://www.nature.com/articles/s41467-021-23905-3](URL)
- Climate change is one of the most pressing environmental problems of our times. According to the Inter-governmental Panel of Climate Change (IPCC) sixth report, "emissions of greenhouse gases from human activities are responsible for approximately 1.1°C of warming since 1850-1900", and on average over the next 20 years, "global temperature is expected to reach or exceed 1.5°C of warming". This degree of warming will cause increasing heat waves, shorter cold seasons and longer warm season. [https://www.ipcc.ch/2021/08/09/ar6-wg1-20210809-pr/](URL)
- Deforestation is driven by agricultural expansion, increasing urbanization and illegal logging and mining around the world, and it has important consequences on biodiversity losses and climate change. [https://www.conservation.org/stories/11-deforestation-facts-you-need-to-know](URL)

## Contributions of Environmental Statistics to Statistical Sciences

There are many problems in statistical sciences that were originally proposed as solutions to important environmental problems as:

* Spatial statistics and geostatistics
* Spatio-temporal models
* Extreme value analysis
* Change-point detection
* Hierarchical Bayesian models
* Measurement-error models
* Missing-data methods
* Risk assessment methodologies
* Environmental monitoring design

The wide range of problems analyzed within this field has created close connections with other statistical science domains as spatial statistics, data science, and environmental informatics.

The aim of Environmental Statistics is to provide adequate tools concerned with the collection, analysis, interpretation, and modeling of data describing environmental systems, ecological processes, natural resources, environmental hazards, climate variability and change, pollution and the interactions of human activities and the natural environment.
